import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function why() {
  return (
    <div className={styles.container}>
    <div className={styles.topnav}>
          <a href="/" >Home</a>
          <a href="#" className={styles.active} >Post</a>
          <a href="#">Project</a>
          <img className={styles.logo_me} src="/vercel2.svg"></img>
    </div>
      <Head>
        <title>Post || learn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            
      <main className={styles.main}>
        <h1 className={styles.title}>
          Gatau mau nulis apaan wkwkw 
        </h1>

        <p className={styles.description}>
          Just editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
      <p>

      </p>
    <p className={styles.article}>
    <h1>Learn Next-js</h1>
    <hr className={styles.hrlong} />
                hhii im naufal hubab abdillah from nextjshii im naufal hubab abdillah from nextjsii im naufal hubab abdillah from nextjs
</p>


      </main>

      <footer className={styles.footer}>
        <a
  href =
      "https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  target = "_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={
    16} />
          </span>
            &nbsp; and <font className={styles.next}>&nbsp;Next.js</font> 

        </a>
      </footer>
    </div>
  )
}
