import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import Link from 'next/link'
import profilepic from '../public/gitpp.png'
export default function Home() {
  return (
    <Layout title="Home">
    <div className={styles.topnav}>
            <Link href="/">
              <a className={styles.active}>Home</a>
             </Link>
            <Link href="/blog/learn/sec1">
              <a>Post</a>
             </Link>
          <a href="#">Project</a>
           <img className={styles.logo_me} src="/vercel2.svg"></img>
    </div>
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <span className={styles.hero}>
              <Image src={profilepic}
                     alt="Author profile pic" 
                     className={styles.hero}
                />
        </span>
    <h1 className={styles.title}>
          Hello there!
        </h1>
        <p className={styles.description}>
          Just editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
    <h1>Learn Next-js</h1>
    <hr className={styles.hrlong} />
    <p className={styles.article}>
    im curently learn Next-js
    </p>

        <div className={styles.grid}>

          <a href="/blog/learn2" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Navigating</p>
          </a>


        </div>
      </main>

    </div>
    </Layout>
  )
}
